name: pext
description: Static front-end prototype for PEXT coextrusion operations.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dio: ^5.7.0
  http_parser: ^4.1.2
  file_picker: ^13.1.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/
    - icons/chat/
    - icons/common/
    - icons/home/
    - icons/navigation/
    - icons/resins/
    - images/
